### ISSUE TITLE
Home Screen Widget rebuilding frequently

### ISSUE THREAD

**Issue by Nitin-Poojary** [RivaanRanawat/flutter-reddit-clone#4]
### Performance issue

In main.dart file 
```
void getData(WidgetRef ref, User data) async {
    userModel = await ref.watch(authControllerProvider.notifier).getUserData(data.uid).first;
    ref.read(userProvider.notifier).update((state) => userModel);
    setState(() {});
  }

```

This function is calling setState((){}) which leads to rebuilding build function in main.dart which is again calling getData() function in MaterialApp.router
```
if (data != null) {
                  getData(ref, data);
                  if (userModel != null) {
                    return loggedInRoute;
                  }
                }
```

Which leads to rebuilding of whole app frequently and causing wastage of  resources to rebuild widgets without any change in state or incoming data from firebase.

**Comment by RivaanRanawat** [comment]
Thanks for resolving this issue Nitin. Much appreciated!
